# Generated by Django 3.2.5 on 2021-07-28 10:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_invite_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
    ]
